<?php
defined('BASEPATH') OR exit('No direct script access allowed');


class Iframe extends CI_Controller
{
	
	    function __construct() {
        parent::__construct ();
        // load the pdo for db connection
        $this->pdo = $this->load->database ( 'pdo', true );
		$this->load->helper ( 'form' );
        $this->load->library ( 'session' );
		$this->load->model('Site_model');
        $this->load->library('upload');
       include ('application/libraries/Pesapal_oauth.php');
	
    }

	public function index() {

        //$order_details = $this->input->post('form_data');
       // parse_str($order_details);

        //$this->load->library('session');
       // $this->session->set_userdata('order_details', $order_details);

      //  $this->load->library('license');
        // Generate unique payment ID
       // $rand = $this->license->random_gen('8');
        $payment_number = 'Order';

		//pesapal params
		$token = $params = NULL;

		/*
		PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
		when you are ready to go live change to https://www.pesapal.com.
		*/
		$consumer_key = 'UNBdLrQq/MayDAnUW3bqZyEaZS2ryGNS';//Register a merchant account on
		                   //demo.pesapal.com and use the merchant key for testing.
		                   //When you are ready to go live make sure you change the key to the live account
		                   //registered on www.pesapal.com!
		$consumer_secret = 'OluhPGmT+Ee+OxfqIP9Wb1NNY8k=';// Use the secret from your test
		                   //account on demo.pesapal.com. When you are ready to go live make sure you 
		                   //change the secret to the live account registered on www.pesapal.com!
		$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
		$iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
		                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

		//get form details
		$amount = 40;
		$desc = 'rer';
		$type = 'MERCHANT'; //default value = MERCHANT
		$reference = $payment_number;//unique order id of the transaction, generated by merchant
		$first_name = 'Timothy';
		$last_name = 'maruti';
		//$email = $email;
		$phonenumber = '0716099901';//ONE of email or phonenumber is required
        $currency = 'USD';
        // Conver to amount to KES
        if($resp = @file_get_contents('https://www.nurucoin.com/exchange/usd')){
            if($arr = json_decode($resp)){
                if($exc_rate = $arr->value){
                    $amount = ceil($amount * $exc_rate);
                    $currency = 'KES';

                }
            }
        }

		$callback_url = base_url('make-an-order/'.$productId); //redirect url, the page that will handle the response from pesapal.

		$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Currency=\"".$currency."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);

		$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);

    
		//display pesapal - iframe and pass iframe_src
       // $this->load->view('pesapal/iframe', ['src'=>$iframe_src]);
	   echo $iframe_src;

    }
}